// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent.proto

package protodata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindAgentsRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindAgentsRequest) Reset()         { *m = FindAgentsRequest{} }
func (m *FindAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAgentsRequest) ProtoMessage()    {}
func (*FindAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{0}
}

func (m *FindAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAgentsRequest.Unmarshal(m, b)
}
func (m *FindAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAgentsRequest.Marshal(b, m, deterministic)
}
func (m *FindAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAgentsRequest.Merge(m, src)
}
func (m *FindAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAgentsRequest.Size(m)
}
func (m *FindAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAgentsRequest proto.InternalMessageInfo

func (m *FindAgentsRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *FindAgentsRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

type FindAgentsResponse struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAgentsResponse) Reset()         { *m = FindAgentsResponse{} }
func (m *FindAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAgentsResponse) ProtoMessage()    {}
func (*FindAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{1}
}

func (m *FindAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAgentsResponse.Unmarshal(m, b)
}
func (m *FindAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAgentsResponse.Marshal(b, m, deterministic)
}
func (m *FindAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAgentsResponse.Merge(m, src)
}
func (m *FindAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAgentsResponse.Size(m)
}
func (m *FindAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAgentsResponse proto.InternalMessageInfo

func (m *FindAgentsResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type NotifyAgentUpRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Interval             int32       `protobuf:"varint,3,opt,name=interval,proto3" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NotifyAgentUpRequest) Reset()         { *m = NotifyAgentUpRequest{} }
func (m *NotifyAgentUpRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyAgentUpRequest) ProtoMessage()    {}
func (*NotifyAgentUpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{2}
}

func (m *NotifyAgentUpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAgentUpRequest.Unmarshal(m, b)
}
func (m *NotifyAgentUpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAgentUpRequest.Marshal(b, m, deterministic)
}
func (m *NotifyAgentUpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAgentUpRequest.Merge(m, src)
}
func (m *NotifyAgentUpRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyAgentUpRequest.Size(m)
}
func (m *NotifyAgentUpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAgentUpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAgentUpRequest proto.InternalMessageInfo

func (m *NotifyAgentUpRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *NotifyAgentUpRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *NotifyAgentUpRequest) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

type NotifyAgentUpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyAgentUpResponse) Reset()         { *m = NotifyAgentUpResponse{} }
func (m *NotifyAgentUpResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyAgentUpResponse) ProtoMessage()    {}
func (*NotifyAgentUpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{3}
}

func (m *NotifyAgentUpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAgentUpResponse.Unmarshal(m, b)
}
func (m *NotifyAgentUpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAgentUpResponse.Marshal(b, m, deterministic)
}
func (m *NotifyAgentUpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAgentUpResponse.Merge(m, src)
}
func (m *NotifyAgentUpResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyAgentUpResponse.Size(m)
}
func (m *NotifyAgentUpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAgentUpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAgentUpResponse proto.InternalMessageInfo

type NotifyAgentDownRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NotifyAgentDownRequest) Reset()         { *m = NotifyAgentDownRequest{} }
func (m *NotifyAgentDownRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyAgentDownRequest) ProtoMessage()    {}
func (*NotifyAgentDownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{4}
}

func (m *NotifyAgentDownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAgentDownRequest.Unmarshal(m, b)
}
func (m *NotifyAgentDownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAgentDownRequest.Marshal(b, m, deterministic)
}
func (m *NotifyAgentDownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAgentDownRequest.Merge(m, src)
}
func (m *NotifyAgentDownRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyAgentDownRequest.Size(m)
}
func (m *NotifyAgentDownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAgentDownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAgentDownRequest proto.InternalMessageInfo

func (m *NotifyAgentDownRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *NotifyAgentDownRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type NotifyAgentDownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyAgentDownResponse) Reset()         { *m = NotifyAgentDownResponse{} }
func (m *NotifyAgentDownResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyAgentDownResponse) ProtoMessage()    {}
func (*NotifyAgentDownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{5}
}

func (m *NotifyAgentDownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyAgentDownResponse.Unmarshal(m, b)
}
func (m *NotifyAgentDownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyAgentDownResponse.Marshal(b, m, deterministic)
}
func (m *NotifyAgentDownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyAgentDownResponse.Merge(m, src)
}
func (m *NotifyAgentDownResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyAgentDownResponse.Size(m)
}
func (m *NotifyAgentDownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyAgentDownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyAgentDownResponse proto.InternalMessageInfo

type ChangeSyncStatusRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Status               string      `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ChangeSyncStatusRequest) Reset()         { *m = ChangeSyncStatusRequest{} }
func (m *ChangeSyncStatusRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeSyncStatusRequest) ProtoMessage()    {}
func (*ChangeSyncStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{6}
}

func (m *ChangeSyncStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSyncStatusRequest.Unmarshal(m, b)
}
func (m *ChangeSyncStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSyncStatusRequest.Marshal(b, m, deterministic)
}
func (m *ChangeSyncStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSyncStatusRequest.Merge(m, src)
}
func (m *ChangeSyncStatusRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeSyncStatusRequest.Size(m)
}
func (m *ChangeSyncStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSyncStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSyncStatusRequest proto.InternalMessageInfo

func (m *ChangeSyncStatusRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *ChangeSyncStatusRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *ChangeSyncStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type ChangeSyncStatusResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeSyncStatusResponse) Reset()         { *m = ChangeSyncStatusResponse{} }
func (m *ChangeSyncStatusResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeSyncStatusResponse) ProtoMessage()    {}
func (*ChangeSyncStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{7}
}

func (m *ChangeSyncStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeSyncStatusResponse.Unmarshal(m, b)
}
func (m *ChangeSyncStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeSyncStatusResponse.Marshal(b, m, deterministic)
}
func (m *ChangeSyncStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeSyncStatusResponse.Merge(m, src)
}
func (m *ChangeSyncStatusResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeSyncStatusResponse.Size(m)
}
func (m *ChangeSyncStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeSyncStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeSyncStatusResponse proto.InternalMessageInfo

type FindAllAgentsRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindAllAgentsRequest) Reset()         { *m = FindAllAgentsRequest{} }
func (m *FindAllAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllAgentsRequest) ProtoMessage()    {}
func (*FindAllAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{8}
}

func (m *FindAllAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllAgentsRequest.Unmarshal(m, b)
}
func (m *FindAllAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllAgentsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllAgentsRequest.Merge(m, src)
}
func (m *FindAllAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllAgentsRequest.Size(m)
}
func (m *FindAllAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllAgentsRequest proto.InternalMessageInfo

func (m *FindAllAgentsRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type FindAllAgentsResponse struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAllAgentsResponse) Reset()         { *m = FindAllAgentsResponse{} }
func (m *FindAllAgentsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllAgentsResponse) ProtoMessage()    {}
func (*FindAllAgentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{9}
}

func (m *FindAllAgentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllAgentsResponse.Unmarshal(m, b)
}
func (m *FindAllAgentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllAgentsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllAgentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllAgentsResponse.Merge(m, src)
}
func (m *FindAllAgentsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllAgentsResponse.Size(m)
}
func (m *FindAllAgentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllAgentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllAgentsResponse proto.InternalMessageInfo

func (m *FindAllAgentsResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

type FindAgentsByTelegrafConfigIDRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,2,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindAgentsByTelegrafConfigIDRequest) Reset()         { *m = FindAgentsByTelegrafConfigIDRequest{} }
func (m *FindAgentsByTelegrafConfigIDRequest) String() string { return proto.CompactTextString(m) }
func (*FindAgentsByTelegrafConfigIDRequest) ProtoMessage()    {}
func (*FindAgentsByTelegrafConfigIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{10}
}

func (m *FindAgentsByTelegrafConfigIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest.Unmarshal(m, b)
}
func (m *FindAgentsByTelegrafConfigIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest.Marshal(b, m, deterministic)
}
func (m *FindAgentsByTelegrafConfigIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest.Merge(m, src)
}
func (m *FindAgentsByTelegrafConfigIDRequest) XXX_Size() int {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest.Size(m)
}
func (m *FindAgentsByTelegrafConfigIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAgentsByTelegrafConfigIDRequest proto.InternalMessageInfo

func (m *FindAgentsByTelegrafConfigIDRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *FindAgentsByTelegrafConfigIDRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type FindAgentsByTelegrafConfigIDResponse struct {
	Agents               []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindAgentsByTelegrafConfigIDResponse) Reset()         { *m = FindAgentsByTelegrafConfigIDResponse{} }
func (m *FindAgentsByTelegrafConfigIDResponse) String() string { return proto.CompactTextString(m) }
func (*FindAgentsByTelegrafConfigIDResponse) ProtoMessage()    {}
func (*FindAgentsByTelegrafConfigIDResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_56ede974c0020f77, []int{11}
}

func (m *FindAgentsByTelegrafConfigIDResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse.Unmarshal(m, b)
}
func (m *FindAgentsByTelegrafConfigIDResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse.Marshal(b, m, deterministic)
}
func (m *FindAgentsByTelegrafConfigIDResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse.Merge(m, src)
}
func (m *FindAgentsByTelegrafConfigIDResponse) XXX_Size() int {
	return xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse.Size(m)
}
func (m *FindAgentsByTelegrafConfigIDResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAgentsByTelegrafConfigIDResponse proto.InternalMessageInfo

func (m *FindAgentsByTelegrafConfigIDResponse) GetAgents() []*Agent {
	if m != nil {
		return m.Agents
	}
	return nil
}

func init() {
	proto.RegisterType((*FindAgentsRequest)(nil), "protodata.FindAgentsRequest")
	proto.RegisterType((*FindAgentsResponse)(nil), "protodata.FindAgentsResponse")
	proto.RegisterType((*NotifyAgentUpRequest)(nil), "protodata.NotifyAgentUpRequest")
	proto.RegisterType((*NotifyAgentUpResponse)(nil), "protodata.NotifyAgentUpResponse")
	proto.RegisterType((*NotifyAgentDownRequest)(nil), "protodata.NotifyAgentDownRequest")
	proto.RegisterType((*NotifyAgentDownResponse)(nil), "protodata.NotifyAgentDownResponse")
	proto.RegisterType((*ChangeSyncStatusRequest)(nil), "protodata.ChangeSyncStatusRequest")
	proto.RegisterType((*ChangeSyncStatusResponse)(nil), "protodata.ChangeSyncStatusResponse")
	proto.RegisterType((*FindAllAgentsRequest)(nil), "protodata.FindAllAgentsRequest")
	proto.RegisterType((*FindAllAgentsResponse)(nil), "protodata.FindAllAgentsResponse")
	proto.RegisterType((*FindAgentsByTelegrafConfigIDRequest)(nil), "protodata.FindAgentsByTelegrafConfigIDRequest")
	proto.RegisterType((*FindAgentsByTelegrafConfigIDResponse)(nil), "protodata.FindAgentsByTelegrafConfigIDResponse")
}

func init() { proto.RegisterFile("agent.proto", fileDescriptor_56ede974c0020f77) }

var fileDescriptor_56ede974c0020f77 = []byte{
	// 483 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x69, 0x1b, 0x91, 0x09, 0x15, 0x61, 0x95, 0x34, 0x66, 0x55, 0x84, 0xd9, 0xf6, 0x60,
	0x38, 0x04, 0x29, 0xdc, 0x11, 0xa6, 0x11, 0x52, 0x85, 0x84, 0x90, 0x13, 0x2e, 0x48, 0x08, 0x2d,
	0xc9, 0x26, 0xb1, 0x94, 0xec, 0x06, 0x7b, 0x5c, 0x30, 0x9c, 0xf8, 0x71, 0xfc, 0x2f, 0x94, 0x8d,
	0xeb, 0xae, 0x1d, 0xc7, 0x22, 0x55, 0x4e, 0xd6, 0x7c, 0xbc, 0x79, 0xcf, 0xb3, 0x6f, 0xa0, 0xc1,
	0xa7, 0x42, 0x62, 0x77, 0x19, 0x2a, 0x54, 0xa4, 0xae, 0x3f, 0x63, 0x8e, 0x9c, 0x02, 0x8f, 0x71,
	0xb6, 0x4e, 0xd3, 0x07, 0x42, 0x62, 0x80, 0xc9, 0x3a, 0x62, 0x23, 0x78, 0xf4, 0x2e, 0x90, 0x63,
	0x6f, 0x85, 0x8b, 0x7c, 0xf1, 0x3d, 0x16, 0x11, 0x12, 0x17, 0x8e, 0x56, 0x00, 0xdb, 0x72, 0x2c,
	0xb7, 0xd1, 0x6b, 0x75, 0xb3, 0x41, 0x5d, 0x6f, 0xbc, 0x08, 0xa4, 0x17, 0xe3, 0xcc, 0xd7, 0x1d,
	0xe4, 0x02, 0x4e, 0x7e, 0x2d, 0x94, 0xf4, 0x46, 0x23, 0x15, 0x4b, 0xbc, 0xea, 0xdb, 0xf7, 0x1c,
	0xcb, 0xad, 0xfb, 0xf9, 0x24, 0x7b, 0x0d, 0xc4, 0x24, 0x89, 0x96, 0x4a, 0x46, 0x82, 0xb8, 0x50,
	0xd3, 0x72, 0x23, 0xdb, 0x72, 0x0e, 0xdd, 0x46, 0xaf, 0x69, 0xf2, 0xac, 0x0a, 0x7e, 0x5a, 0x67,
	0x09, 0xb4, 0x3e, 0x28, 0x0c, 0x26, 0x89, 0x4e, 0x7f, 0x5a, 0xde, 0xe8, 0x7c, 0x9e, 0xd3, 0xd9,
	0x36, 0xf0, 0x43, 0x21, 0xb9, 0x44, 0x43, 0x28, 0x85, 0xfb, 0x33, 0x15, 0xa1, 0xe4, 0x0b, 0x91,
	0x6a, 0xcc, 0xe2, 0x55, 0x2d, 0x90, 0x28, 0xc2, 0x6b, 0x3e, 0xb7, 0x0f, 0x1d, 0xcb, 0x3d, 0xf6,
	0xb3, 0x98, 0x75, 0xa0, 0x5d, 0xa0, 0x5e, 0xab, 0x67, 0x5f, 0xe1, 0xd4, 0x28, 0xf4, 0xd5, 0x0f,
	0xb9, 0x5f, 0x55, 0xec, 0x31, 0x74, 0x36, 0x08, 0x52, 0xee, 0x9f, 0xd0, 0xb9, 0x9c, 0x71, 0x39,
	0x15, 0x83, 0x44, 0x8e, 0x06, 0xc8, 0x31, 0x8e, 0xf6, 0xbc, 0x92, 0x53, 0xa8, 0x45, 0x7a, 0xae,
	0x5e, 0x48, 0xdd, 0x4f, 0x23, 0x46, 0xc1, 0xde, 0x64, 0x4e, 0x55, 0xbd, 0x81, 0x96, 0x7e, 0xe5,
	0xf9, 0xfc, 0x8e, 0x6e, 0x62, 0x1e, 0xb4, 0x0b, 0x13, 0x76, 0xb6, 0xca, 0x6f, 0x38, 0xbf, 0xb5,
	0xda, 0xdb, 0x64, 0x28, 0xe6, 0x62, 0x1a, 0xf2, 0xc9, 0xa5, 0x92, 0x93, 0x60, 0x7a, 0xd5, 0xdf,
	0xdd, 0xe1, 0x2f, 0xa0, 0x89, 0x85, 0x21, 0x7a, 0x5b, 0xc7, 0xfe, 0x46, 0x9e, 0x7d, 0x84, 0x8b,
	0x6a, 0xf2, 0x5d, 0x7f, 0xa7, 0xf7, 0xf7, 0x08, 0x1a, 0x3a, 0x33, 0x10, 0xe1, 0xb5, 0x08, 0xc9,
	0x7b, 0x80, 0x5b, 0x06, 0x72, 0x66, 0xe0, 0x36, 0xae, 0x98, 0x3e, 0xd9, 0x52, 0x4d, 0x9f, 0xeb,
	0x80, 0x0c, 0xe1, 0x24, 0xe7, 0x6d, 0xf2, 0xd4, 0x40, 0x94, 0x1d, 0x1c, 0x75, 0xb6, 0x37, 0x64,
	0x53, 0x3f, 0xc3, 0xc3, 0x82, 0x6f, 0xc9, 0xb3, 0x72, 0x98, 0x71, 0x34, 0x94, 0x55, 0xb5, 0x64,
	0xb3, 0xbf, 0x40, 0xb3, 0x68, 0x3f, 0x62, 0x22, 0xb7, 0x5c, 0x05, 0x3d, 0xaf, 0xec, 0x31, 0x17,
	0x92, 0xf3, 0x5f, 0x6e, 0x21, 0x65, 0xde, 0xce, 0x2d, 0xa4, 0xd4, 0xba, 0xec, 0x80, 0xfc, 0xb1,
	0xe0, 0xac, 0xca, 0x16, 0xa4, 0x5b, 0xfa, 0x50, 0x5b, 0xcd, 0x4b, 0x5f, 0xfe, 0x77, 0xff, 0x8d,
	0x86, 0x6f, 0x35, 0x8d, 0x78, 0xf5, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xeb, 0x4b, 0x1d, 0x21,
	0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentServerClient is the client API for AgentServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentServerClient interface {
	FindAgents(ctx context.Context, in *FindAgentsRequest, opts ...grpc.CallOption) (*FindAgentsResponse, error)
	NotifyAgentUp(ctx context.Context, in *NotifyAgentUpRequest, opts ...grpc.CallOption) (*NotifyAgentUpResponse, error)
	NotifyAgentDown(ctx context.Context, in *NotifyAgentDownRequest, opts ...grpc.CallOption) (*NotifyAgentDownResponse, error)
	ChangeSyncStatus(ctx context.Context, in *ChangeSyncStatusRequest, opts ...grpc.CallOption) (*ChangeSyncStatusResponse, error)
	FindAllAgents(ctx context.Context, in *FindAllAgentsRequest, opts ...grpc.CallOption) (*FindAllAgentsResponse, error)
	FindAgentsByTelegrafConfigID(ctx context.Context, in *FindAgentsByTelegrafConfigIDRequest, opts ...grpc.CallOption) (*FindAgentsByTelegrafConfigIDResponse, error)
}

type agentServerClient struct {
	cc *grpc.ClientConn
}

func NewAgentServerClient(cc *grpc.ClientConn) AgentServerClient {
	return &agentServerClient{cc}
}

func (c *agentServerClient) FindAgents(ctx context.Context, in *FindAgentsRequest, opts ...grpc.CallOption) (*FindAgentsResponse, error) {
	out := new(FindAgentsResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/FindAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServerClient) NotifyAgentUp(ctx context.Context, in *NotifyAgentUpRequest, opts ...grpc.CallOption) (*NotifyAgentUpResponse, error) {
	out := new(NotifyAgentUpResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/NotifyAgentUp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServerClient) NotifyAgentDown(ctx context.Context, in *NotifyAgentDownRequest, opts ...grpc.CallOption) (*NotifyAgentDownResponse, error) {
	out := new(NotifyAgentDownResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/NotifyAgentDown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServerClient) ChangeSyncStatus(ctx context.Context, in *ChangeSyncStatusRequest, opts ...grpc.CallOption) (*ChangeSyncStatusResponse, error) {
	out := new(ChangeSyncStatusResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/ChangeSyncStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServerClient) FindAllAgents(ctx context.Context, in *FindAllAgentsRequest, opts ...grpc.CallOption) (*FindAllAgentsResponse, error) {
	out := new(FindAllAgentsResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/FindAllAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentServerClient) FindAgentsByTelegrafConfigID(ctx context.Context, in *FindAgentsByTelegrafConfigIDRequest, opts ...grpc.CallOption) (*FindAgentsByTelegrafConfigIDResponse, error) {
	out := new(FindAgentsByTelegrafConfigIDResponse)
	err := c.cc.Invoke(ctx, "/protodata.AgentServer/FindAgentsByTelegrafConfigID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServerServer is the server API for AgentServer service.
type AgentServerServer interface {
	FindAgents(context.Context, *FindAgentsRequest) (*FindAgentsResponse, error)
	NotifyAgentUp(context.Context, *NotifyAgentUpRequest) (*NotifyAgentUpResponse, error)
	NotifyAgentDown(context.Context, *NotifyAgentDownRequest) (*NotifyAgentDownResponse, error)
	ChangeSyncStatus(context.Context, *ChangeSyncStatusRequest) (*ChangeSyncStatusResponse, error)
	FindAllAgents(context.Context, *FindAllAgentsRequest) (*FindAllAgentsResponse, error)
	FindAgentsByTelegrafConfigID(context.Context, *FindAgentsByTelegrafConfigIDRequest) (*FindAgentsByTelegrafConfigIDResponse, error)
}

func RegisterAgentServerServer(s *grpc.Server, srv AgentServerServer) {
	s.RegisterService(&_AgentServer_serviceDesc, srv)
}

func _AgentServer_FindAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).FindAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/FindAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).FindAgents(ctx, req.(*FindAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentServer_NotifyAgentUp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAgentUpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).NotifyAgentUp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/NotifyAgentUp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).NotifyAgentUp(ctx, req.(*NotifyAgentUpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentServer_NotifyAgentDown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyAgentDownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).NotifyAgentDown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/NotifyAgentDown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).NotifyAgentDown(ctx, req.(*NotifyAgentDownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentServer_ChangeSyncStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeSyncStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).ChangeSyncStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/ChangeSyncStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).ChangeSyncStatus(ctx, req.(*ChangeSyncStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentServer_FindAllAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).FindAllAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/FindAllAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).FindAllAgents(ctx, req.(*FindAllAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentServer_FindAgentsByTelegrafConfigID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAgentsByTelegrafConfigIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServerServer).FindAgentsByTelegrafConfigID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.AgentServer/FindAgentsByTelegrafConfigID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServerServer).FindAgentsByTelegrafConfigID(ctx, req.(*FindAgentsByTelegrafConfigIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AgentServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodata.AgentServer",
	HandlerType: (*AgentServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAgents",
			Handler:    _AgentServer_FindAgents_Handler,
		},
		{
			MethodName: "NotifyAgentUp",
			Handler:    _AgentServer_NotifyAgentUp_Handler,
		},
		{
			MethodName: "NotifyAgentDown",
			Handler:    _AgentServer_NotifyAgentDown_Handler,
		},
		{
			MethodName: "ChangeSyncStatus",
			Handler:    _AgentServer_ChangeSyncStatus_Handler,
		},
		{
			MethodName: "FindAllAgents",
			Handler:    _AgentServer_FindAllAgents_Handler,
		},
		{
			MethodName: "FindAgentsByTelegrafConfigID",
			Handler:    _AgentServer_FindAgentsByTelegrafConfigID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
