// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package protodata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TenantAuth struct {
	ZmonAccountID        string   `protobuf:"bytes,1,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TenantAuth) Reset()         { *m = TenantAuth{} }
func (m *TenantAuth) String() string { return proto.CompactTextString(m) }
func (*TenantAuth) ProtoMessage()    {}
func (*TenantAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *TenantAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TenantAuth.Unmarshal(m, b)
}
func (m *TenantAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TenantAuth.Marshal(b, m, deterministic)
}
func (m *TenantAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TenantAuth.Merge(m, src)
}
func (m *TenantAuth) XXX_Size() int {
	return xxx_messageInfo_TenantAuth.Size(m)
}
func (m *TenantAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_TenantAuth.DiscardUnknown(m)
}

var xxx_messageInfo_TenantAuth proto.InternalMessageInfo

func (m *TenantAuth) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *TenantAuth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AdminAuth struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminAuth) Reset()         { *m = AdminAuth{} }
func (m *AdminAuth) String() string { return proto.CompactTextString(m) }
func (*AdminAuth) ProtoMessage()    {}
func (*AdminAuth) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *AdminAuth) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminAuth.Unmarshal(m, b)
}
func (m *AdminAuth) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminAuth.Marshal(b, m, deterministic)
}
func (m *AdminAuth) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminAuth.Merge(m, src)
}
func (m *AdminAuth) XXX_Size() int {
	return xxx_messageInfo_AdminAuth.Size(m)
}
func (m *AdminAuth) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminAuth.DiscardUnknown(m)
}

var xxx_messageInfo_AdminAuth proto.InternalMessageInfo

func (m *AdminAuth) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*TenantAuth)(nil), "protodata.TenantAuth")
	proto.RegisterType((*AdminAuth)(nil), "protodata.AdminAuth")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 120 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x04, 0x53, 0x29, 0x89, 0x25, 0x89, 0x4a, 0x1e,
	0x5c, 0x5c, 0x21, 0xa9, 0x79, 0x89, 0x79, 0x25, 0x8e, 0xa5, 0x25, 0x19, 0x42, 0x2a, 0x5c, 0xbc,
	0x55, 0xb9, 0xf9, 0x79, 0x8e, 0xc9, 0xc9, 0xf9, 0xa5, 0x79, 0x25, 0x9e, 0x2e, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x9c, 0x41, 0xa8, 0x82, 0x42, 0x22, 0x5c, 0xac, 0x25, 0xf9, 0xd9, 0xa9, 0x79, 0x12,
	0x4c, 0x60, 0x59, 0x08, 0x47, 0x49, 0x91, 0x8b, 0xd3, 0x31, 0x25, 0x37, 0x33, 0x0f, 0x6c, 0x10,
	0x5c, 0x09, 0x23, 0x92, 0x92, 0x24, 0x36, 0xb0, 0xbd, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x37, 0xf1, 0xeb, 0xb5, 0x8c, 0x00, 0x00, 0x00,
}
