// Code generated by protoc-gen-go. DO NOT EDIT.
// source: command.proto

package protodata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PushConfigUpdateCommandRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AgentID              int32       `protobuf:"varint,2,opt,name=agentID,proto3" json:"agentID,omitempty"`
	TelegrafConfigID     int32       `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushConfigUpdateCommandRequest) Reset()         { *m = PushConfigUpdateCommandRequest{} }
func (m *PushConfigUpdateCommandRequest) String() string { return proto.CompactTextString(m) }
func (*PushConfigUpdateCommandRequest) ProtoMessage()    {}
func (*PushConfigUpdateCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{0}
}

func (m *PushConfigUpdateCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushConfigUpdateCommandRequest.Unmarshal(m, b)
}
func (m *PushConfigUpdateCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushConfigUpdateCommandRequest.Marshal(b, m, deterministic)
}
func (m *PushConfigUpdateCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushConfigUpdateCommandRequest.Merge(m, src)
}
func (m *PushConfigUpdateCommandRequest) XXX_Size() int {
	return xxx_messageInfo_PushConfigUpdateCommandRequest.Size(m)
}
func (m *PushConfigUpdateCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushConfigUpdateCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushConfigUpdateCommandRequest proto.InternalMessageInfo

func (m *PushConfigUpdateCommandRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *PushConfigUpdateCommandRequest) GetAgentID() int32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

func (m *PushConfigUpdateCommandRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type PushConfigUpdateCommandResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushConfigUpdateCommandResponse) Reset()         { *m = PushConfigUpdateCommandResponse{} }
func (m *PushConfigUpdateCommandResponse) String() string { return proto.CompactTextString(m) }
func (*PushConfigUpdateCommandResponse) ProtoMessage()    {}
func (*PushConfigUpdateCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{1}
}

func (m *PushConfigUpdateCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushConfigUpdateCommandResponse.Unmarshal(m, b)
}
func (m *PushConfigUpdateCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushConfigUpdateCommandResponse.Marshal(b, m, deterministic)
}
func (m *PushConfigUpdateCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushConfigUpdateCommandResponse.Merge(m, src)
}
func (m *PushConfigUpdateCommandResponse) XXX_Size() int {
	return xxx_messageInfo_PushConfigUpdateCommandResponse.Size(m)
}
func (m *PushConfigUpdateCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushConfigUpdateCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushConfigUpdateCommandResponse proto.InternalMessageInfo

type PushRestartCommandRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	AgentID              int32       `protobuf:"varint,2,opt,name=agentID,proto3" json:"agentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PushRestartCommandRequest) Reset()         { *m = PushRestartCommandRequest{} }
func (m *PushRestartCommandRequest) String() string { return proto.CompactTextString(m) }
func (*PushRestartCommandRequest) ProtoMessage()    {}
func (*PushRestartCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{2}
}

func (m *PushRestartCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRestartCommandRequest.Unmarshal(m, b)
}
func (m *PushRestartCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRestartCommandRequest.Marshal(b, m, deterministic)
}
func (m *PushRestartCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRestartCommandRequest.Merge(m, src)
}
func (m *PushRestartCommandRequest) XXX_Size() int {
	return xxx_messageInfo_PushRestartCommandRequest.Size(m)
}
func (m *PushRestartCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRestartCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PushRestartCommandRequest proto.InternalMessageInfo

func (m *PushRestartCommandRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *PushRestartCommandRequest) GetAgentID() int32 {
	if m != nil {
		return m.AgentID
	}
	return 0
}

type PushRestartCommandResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushRestartCommandResponse) Reset()         { *m = PushRestartCommandResponse{} }
func (m *PushRestartCommandResponse) String() string { return proto.CompactTextString(m) }
func (*PushRestartCommandResponse) ProtoMessage()    {}
func (*PushRestartCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{3}
}

func (m *PushRestartCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushRestartCommandResponse.Unmarshal(m, b)
}
func (m *PushRestartCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushRestartCommandResponse.Marshal(b, m, deterministic)
}
func (m *PushRestartCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushRestartCommandResponse.Merge(m, src)
}
func (m *PushRestartCommandResponse) XXX_Size() int {
	return xxx_messageInfo_PushRestartCommandResponse.Size(m)
}
func (m *PushRestartCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PushRestartCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PushRestartCommandResponse proto.InternalMessageInfo

type CheckCommandRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CheckCommandRequest) Reset()         { *m = CheckCommandRequest{} }
func (m *CheckCommandRequest) String() string { return proto.CompactTextString(m) }
func (*CheckCommandRequest) ProtoMessage()    {}
func (*CheckCommandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{4}
}

func (m *CheckCommandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckCommandRequest.Unmarshal(m, b)
}
func (m *CheckCommandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckCommandRequest.Marshal(b, m, deterministic)
}
func (m *CheckCommandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckCommandRequest.Merge(m, src)
}
func (m *CheckCommandRequest) XXX_Size() int {
	return xxx_messageInfo_CheckCommandRequest.Size(m)
}
func (m *CheckCommandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckCommandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckCommandRequest proto.InternalMessageInfo

func (m *CheckCommandRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *CheckCommandRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

type CheckCommandResponse struct {
	Command              *Command `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckCommandResponse) Reset()         { *m = CheckCommandResponse{} }
func (m *CheckCommandResponse) String() string { return proto.CompactTextString(m) }
func (*CheckCommandResponse) ProtoMessage()    {}
func (*CheckCommandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_213c0bb044472049, []int{5}
}

func (m *CheckCommandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckCommandResponse.Unmarshal(m, b)
}
func (m *CheckCommandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckCommandResponse.Marshal(b, m, deterministic)
}
func (m *CheckCommandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckCommandResponse.Merge(m, src)
}
func (m *CheckCommandResponse) XXX_Size() int {
	return xxx_messageInfo_CheckCommandResponse.Size(m)
}
func (m *CheckCommandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckCommandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckCommandResponse proto.InternalMessageInfo

func (m *CheckCommandResponse) GetCommand() *Command {
	if m != nil {
		return m.Command
	}
	return nil
}

func init() {
	proto.RegisterType((*PushConfigUpdateCommandRequest)(nil), "protodata.PushConfigUpdateCommandRequest")
	proto.RegisterType((*PushConfigUpdateCommandResponse)(nil), "protodata.PushConfigUpdateCommandResponse")
	proto.RegisterType((*PushRestartCommandRequest)(nil), "protodata.PushRestartCommandRequest")
	proto.RegisterType((*PushRestartCommandResponse)(nil), "protodata.PushRestartCommandResponse")
	proto.RegisterType((*CheckCommandRequest)(nil), "protodata.CheckCommandRequest")
	proto.RegisterType((*CheckCommandResponse)(nil), "protodata.CheckCommandResponse")
}

func init() { proto.RegisterFile("command.proto", fileDescriptor_213c0bb044472049) }

var fileDescriptor_213c0bb044472049 = []byte{
	// 327 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xdf, 0x4e, 0x32, 0x31,
	0x10, 0xc5, 0xbf, 0xe5, 0x53, 0x91, 0x11, 0x12, 0x33, 0x6a, 0x5c, 0x1b, 0x03, 0xb8, 0xd1, 0x04,
	0x88, 0xe1, 0x02, 0x9f, 0xc0, 0xc0, 0x0d, 0x77, 0xba, 0xea, 0x9d, 0x17, 0x56, 0x18, 0x58, 0xa2,
	0xb4, 0xd8, 0xce, 0x9a, 0xf8, 0x18, 0x3e, 0x8f, 0x2f, 0x67, 0xd8, 0x3f, 0x64, 0x15, 0x56, 0x8d,
	0x89, 0x57, 0xcd, 0x4c, 0x4f, 0xcf, 0x6f, 0x72, 0xa6, 0x50, 0x19, 0xe8, 0xe9, 0x54, 0xaa, 0x61,
	0x7b, 0x66, 0x34, 0x6b, 0x2c, 0x45, 0xc7, 0x50, 0xb2, 0x14, 0x20, 0x43, 0x0e, 0xe2, 0xb6, 0x28,
	0x93, 0xe2, 0x09, 0xbf, 0xc4, 0x95, 0xf7, 0xea, 0x40, 0xf5, 0x22, 0xb4, 0x41, 0x57, 0xab, 0xd1,
	0x64, 0x7c, 0x33, 0x1b, 0x4a, 0xa6, 0x6e, 0x6c, 0xe3, 0xd3, 0x53, 0x48, 0x96, 0xb1, 0x09, 0x6b,
	0xf3, 0xe7, 0xae, 0x53, 0x77, 0x1a, 0x5b, 0x9d, 0xbd, 0xf6, 0xc2, 0xb6, 0x7d, 0x4d, 0x4a, 0x2a,
	0x3e, 0x0f, 0x39, 0xf0, 0x23, 0x09, 0xba, 0x50, 0x94, 0x63, 0x52, 0xdc, 0xef, 0xb9, 0x85, 0xba,
	0xd3, 0x58, 0xf7, 0xd3, 0x12, 0x5b, 0xb0, 0xcd, 0xf4, 0x48, 0x63, 0x23, 0x47, 0x31, 0xaa, 0xdf,
	0x73, 0xff, 0x47, 0x92, 0xa5, 0xbe, 0x77, 0x04, 0xb5, 0xdc, 0x91, 0xec, 0x4c, 0x2b, 0x4b, 0xde,
	0x1d, 0x1c, 0xcc, 0x25, 0x3e, 0x59, 0x96, 0x86, 0xff, 0x60, 0x60, 0xef, 0x10, 0xc4, 0x2a, 0x42,
	0xc2, 0xbf, 0x85, 0x9d, 0x6e, 0x40, 0x83, 0x87, 0xdf, 0x93, 0x05, 0x6c, 0x06, 0xda, 0xb2, 0x92,
	0x53, 0x8a, 0xd0, 0x25, 0x7f, 0x51, 0x7b, 0x3d, 0xd8, 0xfd, 0xe8, 0x1e, 0x53, 0xf1, 0x14, 0x8a,
	0xc9, 0x8a, 0x13, 0x02, 0x66, 0x08, 0xa9, 0x38, 0x95, 0x74, 0xde, 0x0a, 0x50, 0x49, 0x9a, 0x57,
	0x64, 0x9e, 0xc9, 0xa0, 0x81, 0xfd, 0x9c, 0x60, 0xb1, 0x99, 0x71, 0xfa, 0xfa, 0x3f, 0x88, 0xd6,
	0x4f, 0xa4, 0x49, 0x4e, 0xff, 0x70, 0x00, 0xb8, 0x9c, 0x23, 0x1e, 0x7f, 0xf2, 0x58, 0xb9, 0x48,
	0x71, 0xf2, 0x8d, 0x6a, 0x01, 0xb9, 0x84, 0x72, 0x36, 0x30, 0xac, 0x66, 0x73, 0x59, 0xde, 0x93,
	0xa8, 0xe5, 0xde, 0xa7, 0x96, 0xf7, 0x1b, 0x91, 0xe2, 0xec, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xd3,
	0x1a, 0x97, 0x01, 0x55, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CommandServerClient is the client API for CommandServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CommandServerClient interface {
	PushConfigUpdateCommand(ctx context.Context, in *PushConfigUpdateCommandRequest, opts ...grpc.CallOption) (*PushConfigUpdateCommandResponse, error)
	PushRestartCommand(ctx context.Context, in *PushRestartCommandRequest, opts ...grpc.CallOption) (*PushRestartCommandResponse, error)
	CheckCommand(ctx context.Context, in *CheckCommandRequest, opts ...grpc.CallOption) (*CheckCommandResponse, error)
}

type commandServerClient struct {
	cc *grpc.ClientConn
}

func NewCommandServerClient(cc *grpc.ClientConn) CommandServerClient {
	return &commandServerClient{cc}
}

func (c *commandServerClient) PushConfigUpdateCommand(ctx context.Context, in *PushConfigUpdateCommandRequest, opts ...grpc.CallOption) (*PushConfigUpdateCommandResponse, error) {
	out := new(PushConfigUpdateCommandResponse)
	err := c.cc.Invoke(ctx, "/protodata.CommandServer/PushConfigUpdateCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServerClient) PushRestartCommand(ctx context.Context, in *PushRestartCommandRequest, opts ...grpc.CallOption) (*PushRestartCommandResponse, error) {
	out := new(PushRestartCommandResponse)
	err := c.cc.Invoke(ctx, "/protodata.CommandServer/PushRestartCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commandServerClient) CheckCommand(ctx context.Context, in *CheckCommandRequest, opts ...grpc.CallOption) (*CheckCommandResponse, error) {
	out := new(CheckCommandResponse)
	err := c.cc.Invoke(ctx, "/protodata.CommandServer/CheckCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommandServerServer is the server API for CommandServer service.
type CommandServerServer interface {
	PushConfigUpdateCommand(context.Context, *PushConfigUpdateCommandRequest) (*PushConfigUpdateCommandResponse, error)
	PushRestartCommand(context.Context, *PushRestartCommandRequest) (*PushRestartCommandResponse, error)
	CheckCommand(context.Context, *CheckCommandRequest) (*CheckCommandResponse, error)
}

func RegisterCommandServerServer(s *grpc.Server, srv CommandServerServer) {
	s.RegisterService(&_CommandServer_serviceDesc, srv)
}

func _CommandServer_PushConfigUpdateCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushConfigUpdateCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServerServer).PushConfigUpdateCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.CommandServer/PushConfigUpdateCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServerServer).PushConfigUpdateCommand(ctx, req.(*PushConfigUpdateCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandServer_PushRestartCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushRestartCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServerServer).PushRestartCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.CommandServer/PushRestartCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServerServer).PushRestartCommand(ctx, req.(*PushRestartCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CommandServer_CheckCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommandServerServer).CheckCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.CommandServer/CheckCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommandServerServer).CheckCommand(ctx, req.(*CheckCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CommandServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodata.CommandServer",
	HandlerType: (*CommandServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushConfigUpdateCommand",
			Handler:    _CommandServer_PushConfigUpdateCommand_Handler,
		},
		{
			MethodName: "PushRestartCommand",
			Handler:    _CommandServer_PushRestartCommand_Handler,
		},
		{
			MethodName: "CheckCommand",
			Handler:    _CommandServer_CheckCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "command.proto",
}
