// Code generated by protoc-gen-go. DO NOT EDIT.
// source: entity.proto

package protodata

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agent struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hostname             string   `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	TelegrafConfigID     int32    `protobuf:"varint,4,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	ZmonAccountID        string   `protobuf:"bytes,5,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	Interval             int32    `protobuf:"varint,6,opt,name=interval,proto3" json:"interval,omitempty"`
	LastActiveChecked    int64    `protobuf:"varint,7,opt,name=lastActiveChecked,proto3" json:"lastActiveChecked,omitempty"`
	IsActive             bool     `protobuf:"varint,8,opt,name=isActive,proto3" json:"isActive,omitempty"`
	SyncStatus           string   `protobuf:"bytes,9,opt,name=syncStatus,proto3" json:"syncStatus,omitempty"`
	Created              int64    `protobuf:"varint,10,opt,name=created,proto3" json:"created,omitempty"`
	LastModified         int64    `protobuf:"varint,11,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Agent) Reset()         { *m = Agent{} }
func (m *Agent) String() string { return proto.CompactTextString(m) }
func (*Agent) ProtoMessage()    {}
func (*Agent) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}

func (m *Agent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agent.Unmarshal(m, b)
}
func (m *Agent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agent.Marshal(b, m, deterministic)
}
func (m *Agent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agent.Merge(m, src)
}
func (m *Agent) XXX_Size() int {
	return xxx_messageInfo_Agent.Size(m)
}
func (m *Agent) XXX_DiscardUnknown() {
	xxx_messageInfo_Agent.DiscardUnknown(m)
}

var xxx_messageInfo_Agent proto.InternalMessageInfo

func (m *Agent) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Agent) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *Agent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Agent) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

func (m *Agent) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *Agent) GetInterval() int32 {
	if m != nil {
		return m.Interval
	}
	return 0
}

func (m *Agent) GetLastActiveChecked() int64 {
	if m != nil {
		return m.LastActiveChecked
	}
	return 0
}

func (m *Agent) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Agent) GetSyncStatus() string {
	if m != nil {
		return m.SyncStatus
	}
	return ""
}

func (m *Agent) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *Agent) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

type TelegrafConfig struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ZmonAccountID        string   `protobuf:"bytes,4,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	Config               string   `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	IsDefault            bool     `protobuf:"varint,7,opt,name=isDefault,proto3" json:"isDefault,omitempty"`
	Created              int64    `protobuf:"varint,8,opt,name=created,proto3" json:"created,omitempty"`
	LastModified         int64    `protobuf:"varint,9,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelegrafConfig) Reset()         { *m = TelegrafConfig{} }
func (m *TelegrafConfig) String() string { return proto.CompactTextString(m) }
func (*TelegrafConfig) ProtoMessage()    {}
func (*TelegrafConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}

func (m *TelegrafConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelegrafConfig.Unmarshal(m, b)
}
func (m *TelegrafConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelegrafConfig.Marshal(b, m, deterministic)
}
func (m *TelegrafConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelegrafConfig.Merge(m, src)
}
func (m *TelegrafConfig) XXX_Size() int {
	return xxx_messageInfo_TelegrafConfig.Size(m)
}
func (m *TelegrafConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_TelegrafConfig.DiscardUnknown(m)
}

var xxx_messageInfo_TelegrafConfig proto.InternalMessageInfo

func (m *TelegrafConfig) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TelegrafConfig) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TelegrafConfig) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *TelegrafConfig) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

func (m *TelegrafConfig) GetIsDefault() bool {
	if m != nil {
		return m.IsDefault
	}
	return false
}

func (m *TelegrafConfig) GetCreated() int64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TelegrafConfig) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

type Command struct {
	ConfigUpdateCommand    *ConfigUpdateCommand    `protobuf:"bytes,1,opt,name=configUpdateCommand,proto3" json:"configUpdateCommand,omitempty"`
	RestartCommand         *RestartCommand         `protobuf:"bytes,2,opt,name=restartCommand,proto3" json:"restartCommand,omitempty"`
	LogUploadCommand       *LogUploadCommand       `protobuf:"bytes,3,opt,name=logUploadCommand,proto3" json:"logUploadCommand,omitempty"`
	TelegrafUpgradeCommand *TelegrafUpgradeCommand `protobuf:"bytes,4,opt,name=telegrafUpgradeCommand,proto3" json:"telegrafUpgradeCommand,omitempty"`
	XXX_NoUnkeyedLiteral   struct{}                `json:"-"`
	XXX_unrecognized       []byte                  `json:"-"`
	XXX_sizecache          int32                   `json:"-"`
}

func (m *Command) Reset()         { *m = Command{} }
func (m *Command) String() string { return proto.CompactTextString(m) }
func (*Command) ProtoMessage()    {}
func (*Command) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{2}
}

func (m *Command) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Command.Unmarshal(m, b)
}
func (m *Command) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Command.Marshal(b, m, deterministic)
}
func (m *Command) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Command.Merge(m, src)
}
func (m *Command) XXX_Size() int {
	return xxx_messageInfo_Command.Size(m)
}
func (m *Command) XXX_DiscardUnknown() {
	xxx_messageInfo_Command.DiscardUnknown(m)
}

var xxx_messageInfo_Command proto.InternalMessageInfo

func (m *Command) GetConfigUpdateCommand() *ConfigUpdateCommand {
	if m != nil {
		return m.ConfigUpdateCommand
	}
	return nil
}

func (m *Command) GetRestartCommand() *RestartCommand {
	if m != nil {
		return m.RestartCommand
	}
	return nil
}

func (m *Command) GetLogUploadCommand() *LogUploadCommand {
	if m != nil {
		return m.LogUploadCommand
	}
	return nil
}

func (m *Command) GetTelegrafUpgradeCommand() *TelegrafUpgradeCommand {
	if m != nil {
		return m.TelegrafUpgradeCommand
	}
	return nil
}

type ConfigUpdateCommand struct {
	TelegrafConfigID     int32    `protobuf:"varint,1,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigUpdateCommand) Reset()         { *m = ConfigUpdateCommand{} }
func (m *ConfigUpdateCommand) String() string { return proto.CompactTextString(m) }
func (*ConfigUpdateCommand) ProtoMessage()    {}
func (*ConfigUpdateCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{3}
}

func (m *ConfigUpdateCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigUpdateCommand.Unmarshal(m, b)
}
func (m *ConfigUpdateCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigUpdateCommand.Marshal(b, m, deterministic)
}
func (m *ConfigUpdateCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigUpdateCommand.Merge(m, src)
}
func (m *ConfigUpdateCommand) XXX_Size() int {
	return xxx_messageInfo_ConfigUpdateCommand.Size(m)
}
func (m *ConfigUpdateCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigUpdateCommand.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigUpdateCommand proto.InternalMessageInfo

func (m *ConfigUpdateCommand) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type RestartCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartCommand) Reset()         { *m = RestartCommand{} }
func (m *RestartCommand) String() string { return proto.CompactTextString(m) }
func (*RestartCommand) ProtoMessage()    {}
func (*RestartCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{4}
}

func (m *RestartCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartCommand.Unmarshal(m, b)
}
func (m *RestartCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartCommand.Marshal(b, m, deterministic)
}
func (m *RestartCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartCommand.Merge(m, src)
}
func (m *RestartCommand) XXX_Size() int {
	return xxx_messageInfo_RestartCommand.Size(m)
}
func (m *RestartCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartCommand.DiscardUnknown(m)
}

var xxx_messageInfo_RestartCommand proto.InternalMessageInfo

type LogUploadCommand struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogUploadCommand) Reset()         { *m = LogUploadCommand{} }
func (m *LogUploadCommand) String() string { return proto.CompactTextString(m) }
func (*LogUploadCommand) ProtoMessage()    {}
func (*LogUploadCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{5}
}

func (m *LogUploadCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogUploadCommand.Unmarshal(m, b)
}
func (m *LogUploadCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogUploadCommand.Marshal(b, m, deterministic)
}
func (m *LogUploadCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogUploadCommand.Merge(m, src)
}
func (m *LogUploadCommand) XXX_Size() int {
	return xxx_messageInfo_LogUploadCommand.Size(m)
}
func (m *LogUploadCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_LogUploadCommand.DiscardUnknown(m)
}

var xxx_messageInfo_LogUploadCommand proto.InternalMessageInfo

type TelegrafUpgradeCommand struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TelegrafUpgradeCommand) Reset()         { *m = TelegrafUpgradeCommand{} }
func (m *TelegrafUpgradeCommand) String() string { return proto.CompactTextString(m) }
func (*TelegrafUpgradeCommand) ProtoMessage()    {}
func (*TelegrafUpgradeCommand) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{6}
}

func (m *TelegrafUpgradeCommand) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TelegrafUpgradeCommand.Unmarshal(m, b)
}
func (m *TelegrafUpgradeCommand) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TelegrafUpgradeCommand.Marshal(b, m, deterministic)
}
func (m *TelegrafUpgradeCommand) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TelegrafUpgradeCommand.Merge(m, src)
}
func (m *TelegrafUpgradeCommand) XXX_Size() int {
	return xxx_messageInfo_TelegrafUpgradeCommand.Size(m)
}
func (m *TelegrafUpgradeCommand) XXX_DiscardUnknown() {
	xxx_messageInfo_TelegrafUpgradeCommand.DiscardUnknown(m)
}

var xxx_messageInfo_TelegrafUpgradeCommand proto.InternalMessageInfo

func (m *TelegrafUpgradeCommand) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Agent)(nil), "protodata.Agent")
	proto.RegisterType((*TelegrafConfig)(nil), "protodata.TelegrafConfig")
	proto.RegisterType((*Command)(nil), "protodata.Command")
	proto.RegisterType((*ConfigUpdateCommand)(nil), "protodata.ConfigUpdateCommand")
	proto.RegisterType((*RestartCommand)(nil), "protodata.RestartCommand")
	proto.RegisterType((*LogUploadCommand)(nil), "protodata.LogUploadCommand")
	proto.RegisterType((*TelegrafUpgradeCommand)(nil), "protodata.TelegrafUpgradeCommand")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xdd, 0x8a, 0xdb, 0x30,
	0x10, 0x85, 0xb1, 0xf3, 0x67, 0xcf, 0x6e, 0x43, 0xaa, 0x85, 0xa0, 0xfe, 0xb0, 0xa4, 0xa6, 0x17,
	0xa1, 0x94, 0x5c, 0x6c, 0x9f, 0xc0, 0x24, 0x50, 0x16, 0x5a, 0x28, 0xea, 0xe6, 0xa2, 0x97, 0xaa,
	0xa5, 0x78, 0x45, 0x1d, 0x29, 0xd8, 0x93, 0xc0, 0xf6, 0xf1, 0xfa, 0x00, 0x7d, 0x83, 0xbe, 0x4b,
	0xc9, 0x6c, 0xec, 0xda, 0xb1, 0xbb, 0x57, 0xf6, 0x1c, 0x8d, 0x3e, 0xe9, 0x1c, 0x46, 0x70, 0xa9,
	0x2d, 0x1a, 0x7c, 0x58, 0xec, 0x72, 0x87, 0x8e, 0x85, 0xf4, 0x51, 0x12, 0x65, 0xf4, 0xc7, 0x87,
	0x41, 0x9c, 0x6a, 0x8b, 0x6c, 0x0c, 0xbe, 0x51, 0xdc, 0x9b, 0x79, 0xf3, 0x81, 0xf0, 0x8d, 0x62,
	0x2f, 0x21, 0xb8, 0x77, 0x05, 0x5a, 0xb9, 0xd5, 0xdc, 0x9f, 0x79, 0xf3, 0x50, 0x54, 0x35, 0x63,
	0xd0, 0x27, 0xbd, 0x47, 0x3a, 0xfd, 0xb3, 0x77, 0x30, 0x41, 0x9d, 0xe9, 0x34, 0x97, 0x9b, 0xa5,
	0xb3, 0x1b, 0x93, 0xde, 0xae, 0x78, 0x9f, 0x68, 0x2d, 0x9d, 0xbd, 0x85, 0x67, 0x3f, 0xb7, 0xce,
	0xc6, 0x49, 0xe2, 0xf6, 0x16, 0x6f, 0x57, 0x7c, 0x40, 0xa0, 0xa6, 0x78, 0xbc, 0x81, 0xb1, 0xa8,
	0xf3, 0x83, 0xcc, 0xf8, 0x90, 0x48, 0x55, 0xcd, 0xde, 0xc3, 0xf3, 0x4c, 0x16, 0x18, 0x27, 0x68,
	0x0e, 0x7a, 0x79, 0xaf, 0x93, 0x1f, 0x5a, 0xf1, 0xd1, 0xcc, 0x9b, 0xf7, 0x44, 0x7b, 0x81, 0x48,
	0xc5, 0xa3, 0xc4, 0x83, 0x99, 0x37, 0x0f, 0x44, 0x55, 0xb3, 0x6b, 0x80, 0xe2, 0xc1, 0x26, 0x5f,
	0x51, 0xe2, 0xbe, 0xe0, 0x21, 0x5d, 0xa4, 0xa6, 0x30, 0x0e, 0xa3, 0x24, 0xd7, 0x12, 0xb5, 0xe2,
	0x40, 0xfc, 0xb2, 0x64, 0x11, 0x5c, 0x1e, 0x8f, 0xfa, 0xec, 0x94, 0xd9, 0x18, 0xad, 0xf8, 0x05,
	0x2d, 0x37, 0xb4, 0xe8, 0xb7, 0x07, 0xe3, 0xbb, 0x86, 0xfd, 0x56, 0xd0, 0x5d, 0x61, 0xb6, 0x02,
	0xea, 0x77, 0x05, 0x34, 0x85, 0x61, 0x42, 0xcc, 0x53, 0x7e, 0xa7, 0x8a, 0xbd, 0x86, 0xd0, 0x14,
	0x2b, 0xbd, 0x91, 0xfb, 0x0c, 0x29, 0x94, 0x40, 0xfc, 0x13, 0xea, 0x86, 0x82, 0xa7, 0x0d, 0x85,
	0x1d, 0x86, 0x7e, 0xf9, 0x30, 0x5a, 0xba, 0xed, 0x56, 0x5a, 0xc5, 0xbe, 0xc0, 0xd5, 0xe3, 0x89,
	0xeb, 0x9d, 0x92, 0xa8, 0x4f, 0x32, 0x59, 0xbb, 0xb8, 0xb9, 0x5e, 0x54, 0x53, 0xb6, 0x58, 0xb6,
	0xbb, 0x44, 0xd7, 0x56, 0x16, 0xc3, 0x38, 0xd7, 0x05, 0xca, 0x1c, 0x4b, 0x98, 0x4f, 0xb0, 0x17,
	0x35, 0x98, 0x68, 0x34, 0x88, 0xb3, 0x0d, 0xec, 0x23, 0x4c, 0x32, 0x97, 0xae, 0x77, 0x99, 0x93,
	0xaa, 0x84, 0xf4, 0x08, 0xf2, 0xaa, 0x06, 0xf9, 0x74, 0xd6, 0x22, 0x5a, 0x9b, 0xd8, 0x37, 0x98,
	0x96, 0x83, 0xbb, 0xde, 0xa5, 0xb9, 0x54, 0x95, 0xc1, 0x3e, 0xe1, 0xde, 0xd4, 0x70, 0x77, 0x9d,
	0x8d, 0xe2, 0x3f, 0x80, 0x28, 0x86, 0xab, 0x8e, 0x48, 0x3a, 0x9f, 0x90, 0xd7, 0xfd, 0x84, 0xa2,
	0x09, 0x8c, 0x9b, 0x41, 0x44, 0x0c, 0x26, 0xe7, 0xae, 0xa2, 0x1b, 0x98, 0x76, 0x5f, 0xed, 0x38,
	0x05, 0x07, 0x9d, 0x17, 0xc6, 0x59, 0x3a, 0x22, 0x14, 0x65, 0xf9, 0x7d, 0x48, 0xb6, 0x3e, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x61, 0xbe, 0xaa, 0xb2, 0x34, 0x04, 0x00, 0x00,
}
