// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telegraf_config.proto

package protodata

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetTelegrafConfigOnAgentRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Hostname             string      `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	TelegrafConfigID     int32       `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetTelegrafConfigOnAgentRequest) Reset()         { *m = GetTelegrafConfigOnAgentRequest{} }
func (m *GetTelegrafConfigOnAgentRequest) String() string { return proto.CompactTextString(m) }
func (*GetTelegrafConfigOnAgentRequest) ProtoMessage()    {}
func (*GetTelegrafConfigOnAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{0}
}

func (m *GetTelegrafConfigOnAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTelegrafConfigOnAgentRequest.Unmarshal(m, b)
}
func (m *GetTelegrafConfigOnAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTelegrafConfigOnAgentRequest.Marshal(b, m, deterministic)
}
func (m *GetTelegrafConfigOnAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTelegrafConfigOnAgentRequest.Merge(m, src)
}
func (m *GetTelegrafConfigOnAgentRequest) XXX_Size() int {
	return xxx_messageInfo_GetTelegrafConfigOnAgentRequest.Size(m)
}
func (m *GetTelegrafConfigOnAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTelegrafConfigOnAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTelegrafConfigOnAgentRequest proto.InternalMessageInfo

func (m *GetTelegrafConfigOnAgentRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *GetTelegrafConfigOnAgentRequest) GetHostname() string {
	if m != nil {
		return m.Hostname
	}
	return ""
}

func (m *GetTelegrafConfigOnAgentRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type GetTelegrafConfigOnAgentResponse struct {
	TelegrafConfig       *TelegrafConfig `protobuf:"bytes,1,opt,name=telegrafConfig,proto3" json:"telegrafConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTelegrafConfigOnAgentResponse) Reset()         { *m = GetTelegrafConfigOnAgentResponse{} }
func (m *GetTelegrafConfigOnAgentResponse) String() string { return proto.CompactTextString(m) }
func (*GetTelegrafConfigOnAgentResponse) ProtoMessage()    {}
func (*GetTelegrafConfigOnAgentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{1}
}

func (m *GetTelegrafConfigOnAgentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTelegrafConfigOnAgentResponse.Unmarshal(m, b)
}
func (m *GetTelegrafConfigOnAgentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTelegrafConfigOnAgentResponse.Marshal(b, m, deterministic)
}
func (m *GetTelegrafConfigOnAgentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTelegrafConfigOnAgentResponse.Merge(m, src)
}
func (m *GetTelegrafConfigOnAgentResponse) XXX_Size() int {
	return xxx_messageInfo_GetTelegrafConfigOnAgentResponse.Size(m)
}
func (m *GetTelegrafConfigOnAgentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTelegrafConfigOnAgentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTelegrafConfigOnAgentResponse proto.InternalMessageInfo

func (m *GetTelegrafConfigOnAgentResponse) GetTelegrafConfig() *TelegrafConfig {
	if m != nil {
		return m.TelegrafConfig
	}
	return nil
}

type GetTelegrafConfigOnAdminRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,2,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetTelegrafConfigOnAdminRequest) Reset()         { *m = GetTelegrafConfigOnAdminRequest{} }
func (m *GetTelegrafConfigOnAdminRequest) String() string { return proto.CompactTextString(m) }
func (*GetTelegrafConfigOnAdminRequest) ProtoMessage()    {}
func (*GetTelegrafConfigOnAdminRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{2}
}

func (m *GetTelegrafConfigOnAdminRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTelegrafConfigOnAdminRequest.Unmarshal(m, b)
}
func (m *GetTelegrafConfigOnAdminRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTelegrafConfigOnAdminRequest.Marshal(b, m, deterministic)
}
func (m *GetTelegrafConfigOnAdminRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTelegrafConfigOnAdminRequest.Merge(m, src)
}
func (m *GetTelegrafConfigOnAdminRequest) XXX_Size() int {
	return xxx_messageInfo_GetTelegrafConfigOnAdminRequest.Size(m)
}
func (m *GetTelegrafConfigOnAdminRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTelegrafConfigOnAdminRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTelegrafConfigOnAdminRequest proto.InternalMessageInfo

func (m *GetTelegrafConfigOnAdminRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *GetTelegrafConfigOnAdminRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type GetTelegrafConfigOnAdminResponse struct {
	TelegrafConfig       *TelegrafConfig `protobuf:"bytes,1,opt,name=telegrafConfig,proto3" json:"telegrafConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *GetTelegrafConfigOnAdminResponse) Reset()         { *m = GetTelegrafConfigOnAdminResponse{} }
func (m *GetTelegrafConfigOnAdminResponse) String() string { return proto.CompactTextString(m) }
func (*GetTelegrafConfigOnAdminResponse) ProtoMessage()    {}
func (*GetTelegrafConfigOnAdminResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{3}
}

func (m *GetTelegrafConfigOnAdminResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTelegrafConfigOnAdminResponse.Unmarshal(m, b)
}
func (m *GetTelegrafConfigOnAdminResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTelegrafConfigOnAdminResponse.Marshal(b, m, deterministic)
}
func (m *GetTelegrafConfigOnAdminResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTelegrafConfigOnAdminResponse.Merge(m, src)
}
func (m *GetTelegrafConfigOnAdminResponse) XXX_Size() int {
	return xxx_messageInfo_GetTelegrafConfigOnAdminResponse.Size(m)
}
func (m *GetTelegrafConfigOnAdminResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTelegrafConfigOnAdminResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTelegrafConfigOnAdminResponse proto.InternalMessageInfo

func (m *GetTelegrafConfigOnAdminResponse) GetTelegrafConfig() *TelegrafConfig {
	if m != nil {
		return m.TelegrafConfig
	}
	return nil
}

type FindAllTelegrafConfigsRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *FindAllTelegrafConfigsRequest) Reset()         { *m = FindAllTelegrafConfigsRequest{} }
func (m *FindAllTelegrafConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*FindAllTelegrafConfigsRequest) ProtoMessage()    {}
func (*FindAllTelegrafConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{4}
}

func (m *FindAllTelegrafConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllTelegrafConfigsRequest.Unmarshal(m, b)
}
func (m *FindAllTelegrafConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllTelegrafConfigsRequest.Marshal(b, m, deterministic)
}
func (m *FindAllTelegrafConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllTelegrafConfigsRequest.Merge(m, src)
}
func (m *FindAllTelegrafConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_FindAllTelegrafConfigsRequest.Size(m)
}
func (m *FindAllTelegrafConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllTelegrafConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllTelegrafConfigsRequest proto.InternalMessageInfo

func (m *FindAllTelegrafConfigsRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type FindAllTelegrafConfigsResponse struct {
	TelegrafConfigs      []*TelegrafConfig `protobuf:"bytes,1,rep,name=telegrafConfigs,proto3" json:"telegrafConfigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FindAllTelegrafConfigsResponse) Reset()         { *m = FindAllTelegrafConfigsResponse{} }
func (m *FindAllTelegrafConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*FindAllTelegrafConfigsResponse) ProtoMessage()    {}
func (*FindAllTelegrafConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{5}
}

func (m *FindAllTelegrafConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindAllTelegrafConfigsResponse.Unmarshal(m, b)
}
func (m *FindAllTelegrafConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindAllTelegrafConfigsResponse.Marshal(b, m, deterministic)
}
func (m *FindAllTelegrafConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindAllTelegrafConfigsResponse.Merge(m, src)
}
func (m *FindAllTelegrafConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_FindAllTelegrafConfigsResponse.Size(m)
}
func (m *FindAllTelegrafConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindAllTelegrafConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindAllTelegrafConfigsResponse proto.InternalMessageInfo

func (m *FindAllTelegrafConfigsResponse) GetTelegrafConfigs() []*TelegrafConfig {
	if m != nil {
		return m.TelegrafConfigs
	}
	return nil
}

type FindTelegrafConfigsRequest struct {
	Auth                 *TenantAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *FindTelegrafConfigsRequest) Reset()         { *m = FindTelegrafConfigsRequest{} }
func (m *FindTelegrafConfigsRequest) String() string { return proto.CompactTextString(m) }
func (*FindTelegrafConfigsRequest) ProtoMessage()    {}
func (*FindTelegrafConfigsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{6}
}

func (m *FindTelegrafConfigsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTelegrafConfigsRequest.Unmarshal(m, b)
}
func (m *FindTelegrafConfigsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTelegrafConfigsRequest.Marshal(b, m, deterministic)
}
func (m *FindTelegrafConfigsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTelegrafConfigsRequest.Merge(m, src)
}
func (m *FindTelegrafConfigsRequest) XXX_Size() int {
	return xxx_messageInfo_FindTelegrafConfigsRequest.Size(m)
}
func (m *FindTelegrafConfigsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTelegrafConfigsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindTelegrafConfigsRequest proto.InternalMessageInfo

func (m *FindTelegrafConfigsRequest) GetAuth() *TenantAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

type FindTelegrafConfigsResponse struct {
	TelegrafConfigs      []*TelegrafConfig `protobuf:"bytes,1,rep,name=telegrafConfigs,proto3" json:"telegrafConfigs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FindTelegrafConfigsResponse) Reset()         { *m = FindTelegrafConfigsResponse{} }
func (m *FindTelegrafConfigsResponse) String() string { return proto.CompactTextString(m) }
func (*FindTelegrafConfigsResponse) ProtoMessage()    {}
func (*FindTelegrafConfigsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{7}
}

func (m *FindTelegrafConfigsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindTelegrafConfigsResponse.Unmarshal(m, b)
}
func (m *FindTelegrafConfigsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindTelegrafConfigsResponse.Marshal(b, m, deterministic)
}
func (m *FindTelegrafConfigsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindTelegrafConfigsResponse.Merge(m, src)
}
func (m *FindTelegrafConfigsResponse) XXX_Size() int {
	return xxx_messageInfo_FindTelegrafConfigsResponse.Size(m)
}
func (m *FindTelegrafConfigsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FindTelegrafConfigsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FindTelegrafConfigsResponse proto.InternalMessageInfo

func (m *FindTelegrafConfigsResponse) GetTelegrafConfigs() []*TelegrafConfig {
	if m != nil {
		return m.TelegrafConfigs
	}
	return nil
}

type CreateTelegrafConfigRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	Name                 string     `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Config               string     `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateTelegrafConfigRequest) Reset()         { *m = CreateTelegrafConfigRequest{} }
func (m *CreateTelegrafConfigRequest) String() string { return proto.CompactTextString(m) }
func (*CreateTelegrafConfigRequest) ProtoMessage()    {}
func (*CreateTelegrafConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{8}
}

func (m *CreateTelegrafConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTelegrafConfigRequest.Unmarshal(m, b)
}
func (m *CreateTelegrafConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTelegrafConfigRequest.Marshal(b, m, deterministic)
}
func (m *CreateTelegrafConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTelegrafConfigRequest.Merge(m, src)
}
func (m *CreateTelegrafConfigRequest) XXX_Size() int {
	return xxx_messageInfo_CreateTelegrafConfigRequest.Size(m)
}
func (m *CreateTelegrafConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTelegrafConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTelegrafConfigRequest proto.InternalMessageInfo

func (m *CreateTelegrafConfigRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *CreateTelegrafConfigRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *CreateTelegrafConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateTelegrafConfigRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type CreateTelegrafConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTelegrafConfigResponse) Reset()         { *m = CreateTelegrafConfigResponse{} }
func (m *CreateTelegrafConfigResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTelegrafConfigResponse) ProtoMessage()    {}
func (*CreateTelegrafConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{9}
}

func (m *CreateTelegrafConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTelegrafConfigResponse.Unmarshal(m, b)
}
func (m *CreateTelegrafConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTelegrafConfigResponse.Marshal(b, m, deterministic)
}
func (m *CreateTelegrafConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTelegrafConfigResponse.Merge(m, src)
}
func (m *CreateTelegrafConfigResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTelegrafConfigResponse.Size(m)
}
func (m *CreateTelegrafConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTelegrafConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTelegrafConfigResponse proto.InternalMessageInfo

type DuplicateTelegrafConfigRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *DuplicateTelegrafConfigRequest) Reset()         { *m = DuplicateTelegrafConfigRequest{} }
func (m *DuplicateTelegrafConfigRequest) String() string { return proto.CompactTextString(m) }
func (*DuplicateTelegrafConfigRequest) ProtoMessage()    {}
func (*DuplicateTelegrafConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{10}
}

func (m *DuplicateTelegrafConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateTelegrafConfigRequest.Unmarshal(m, b)
}
func (m *DuplicateTelegrafConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateTelegrafConfigRequest.Marshal(b, m, deterministic)
}
func (m *DuplicateTelegrafConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateTelegrafConfigRequest.Merge(m, src)
}
func (m *DuplicateTelegrafConfigRequest) XXX_Size() int {
	return xxx_messageInfo_DuplicateTelegrafConfigRequest.Size(m)
}
func (m *DuplicateTelegrafConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateTelegrafConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateTelegrafConfigRequest proto.InternalMessageInfo

func (m *DuplicateTelegrafConfigRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *DuplicateTelegrafConfigRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *DuplicateTelegrafConfigRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type DuplicateTelegrafConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DuplicateTelegrafConfigResponse) Reset()         { *m = DuplicateTelegrafConfigResponse{} }
func (m *DuplicateTelegrafConfigResponse) String() string { return proto.CompactTextString(m) }
func (*DuplicateTelegrafConfigResponse) ProtoMessage()    {}
func (*DuplicateTelegrafConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{11}
}

func (m *DuplicateTelegrafConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DuplicateTelegrafConfigResponse.Unmarshal(m, b)
}
func (m *DuplicateTelegrafConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DuplicateTelegrafConfigResponse.Marshal(b, m, deterministic)
}
func (m *DuplicateTelegrafConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DuplicateTelegrafConfigResponse.Merge(m, src)
}
func (m *DuplicateTelegrafConfigResponse) XXX_Size() int {
	return xxx_messageInfo_DuplicateTelegrafConfigResponse.Size(m)
}
func (m *DuplicateTelegrafConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DuplicateTelegrafConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DuplicateTelegrafConfigResponse proto.InternalMessageInfo

type UpdateTelegrafConfigRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	Name                 string     `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Config               string     `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateTelegrafConfigRequest) Reset()         { *m = UpdateTelegrafConfigRequest{} }
func (m *UpdateTelegrafConfigRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTelegrafConfigRequest) ProtoMessage()    {}
func (*UpdateTelegrafConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{12}
}

func (m *UpdateTelegrafConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTelegrafConfigRequest.Unmarshal(m, b)
}
func (m *UpdateTelegrafConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTelegrafConfigRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTelegrafConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTelegrafConfigRequest.Merge(m, src)
}
func (m *UpdateTelegrafConfigRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTelegrafConfigRequest.Size(m)
}
func (m *UpdateTelegrafConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTelegrafConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTelegrafConfigRequest proto.InternalMessageInfo

func (m *UpdateTelegrafConfigRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *UpdateTelegrafConfigRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *UpdateTelegrafConfigRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

func (m *UpdateTelegrafConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateTelegrafConfigRequest) GetConfig() string {
	if m != nil {
		return m.Config
	}
	return ""
}

type UpdateTelegrafConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTelegrafConfigResponse) Reset()         { *m = UpdateTelegrafConfigResponse{} }
func (m *UpdateTelegrafConfigResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTelegrafConfigResponse) ProtoMessage()    {}
func (*UpdateTelegrafConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{13}
}

func (m *UpdateTelegrafConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTelegrafConfigResponse.Unmarshal(m, b)
}
func (m *UpdateTelegrafConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTelegrafConfigResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTelegrafConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTelegrafConfigResponse.Merge(m, src)
}
func (m *UpdateTelegrafConfigResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTelegrafConfigResponse.Size(m)
}
func (m *UpdateTelegrafConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTelegrafConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTelegrafConfigResponse proto.InternalMessageInfo

type RemoveTelegrafConfigRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RemoveTelegrafConfigRequest) Reset()         { *m = RemoveTelegrafConfigRequest{} }
func (m *RemoveTelegrafConfigRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveTelegrafConfigRequest) ProtoMessage()    {}
func (*RemoveTelegrafConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{14}
}

func (m *RemoveTelegrafConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTelegrafConfigRequest.Unmarshal(m, b)
}
func (m *RemoveTelegrafConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTelegrafConfigRequest.Marshal(b, m, deterministic)
}
func (m *RemoveTelegrafConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTelegrafConfigRequest.Merge(m, src)
}
func (m *RemoveTelegrafConfigRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveTelegrafConfigRequest.Size(m)
}
func (m *RemoveTelegrafConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTelegrafConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTelegrafConfigRequest proto.InternalMessageInfo

func (m *RemoveTelegrafConfigRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *RemoveTelegrafConfigRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *RemoveTelegrafConfigRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type RemoveTelegrafConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveTelegrafConfigResponse) Reset()         { *m = RemoveTelegrafConfigResponse{} }
func (m *RemoveTelegrafConfigResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveTelegrafConfigResponse) ProtoMessage()    {}
func (*RemoveTelegrafConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{15}
}

func (m *RemoveTelegrafConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveTelegrafConfigResponse.Unmarshal(m, b)
}
func (m *RemoveTelegrafConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveTelegrafConfigResponse.Marshal(b, m, deterministic)
}
func (m *RemoveTelegrafConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveTelegrafConfigResponse.Merge(m, src)
}
func (m *RemoveTelegrafConfigResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveTelegrafConfigResponse.Size(m)
}
func (m *RemoveTelegrafConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveTelegrafConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveTelegrafConfigResponse proto.InternalMessageInfo

type SetDefaultTelegrafConfigRequest struct {
	Auth                 *AdminAuth `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	ZmonAccountID        string     `protobuf:"bytes,2,opt,name=zmonAccountID,proto3" json:"zmonAccountID,omitempty"`
	TelegrafConfigID     int32      `protobuf:"varint,3,opt,name=telegrafConfigID,proto3" json:"telegrafConfigID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SetDefaultTelegrafConfigRequest) Reset()         { *m = SetDefaultTelegrafConfigRequest{} }
func (m *SetDefaultTelegrafConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetDefaultTelegrafConfigRequest) ProtoMessage()    {}
func (*SetDefaultTelegrafConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{16}
}

func (m *SetDefaultTelegrafConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDefaultTelegrafConfigRequest.Unmarshal(m, b)
}
func (m *SetDefaultTelegrafConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDefaultTelegrafConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetDefaultTelegrafConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDefaultTelegrafConfigRequest.Merge(m, src)
}
func (m *SetDefaultTelegrafConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetDefaultTelegrafConfigRequest.Size(m)
}
func (m *SetDefaultTelegrafConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDefaultTelegrafConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetDefaultTelegrafConfigRequest proto.InternalMessageInfo

func (m *SetDefaultTelegrafConfigRequest) GetAuth() *AdminAuth {
	if m != nil {
		return m.Auth
	}
	return nil
}

func (m *SetDefaultTelegrafConfigRequest) GetZmonAccountID() string {
	if m != nil {
		return m.ZmonAccountID
	}
	return ""
}

func (m *SetDefaultTelegrafConfigRequest) GetTelegrafConfigID() int32 {
	if m != nil {
		return m.TelegrafConfigID
	}
	return 0
}

type SetDefaultTelegrafConfigResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetDefaultTelegrafConfigResponse) Reset()         { *m = SetDefaultTelegrafConfigResponse{} }
func (m *SetDefaultTelegrafConfigResponse) String() string { return proto.CompactTextString(m) }
func (*SetDefaultTelegrafConfigResponse) ProtoMessage()    {}
func (*SetDefaultTelegrafConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3591d3dd1cc41165, []int{17}
}

func (m *SetDefaultTelegrafConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetDefaultTelegrafConfigResponse.Unmarshal(m, b)
}
func (m *SetDefaultTelegrafConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetDefaultTelegrafConfigResponse.Marshal(b, m, deterministic)
}
func (m *SetDefaultTelegrafConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetDefaultTelegrafConfigResponse.Merge(m, src)
}
func (m *SetDefaultTelegrafConfigResponse) XXX_Size() int {
	return xxx_messageInfo_SetDefaultTelegrafConfigResponse.Size(m)
}
func (m *SetDefaultTelegrafConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetDefaultTelegrafConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetDefaultTelegrafConfigResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetTelegrafConfigOnAgentRequest)(nil), "protodata.GetTelegrafConfigOnAgentRequest")
	proto.RegisterType((*GetTelegrafConfigOnAgentResponse)(nil), "protodata.GetTelegrafConfigOnAgentResponse")
	proto.RegisterType((*GetTelegrafConfigOnAdminRequest)(nil), "protodata.GetTelegrafConfigOnAdminRequest")
	proto.RegisterType((*GetTelegrafConfigOnAdminResponse)(nil), "protodata.GetTelegrafConfigOnAdminResponse")
	proto.RegisterType((*FindAllTelegrafConfigsRequest)(nil), "protodata.FindAllTelegrafConfigsRequest")
	proto.RegisterType((*FindAllTelegrafConfigsResponse)(nil), "protodata.FindAllTelegrafConfigsResponse")
	proto.RegisterType((*FindTelegrafConfigsRequest)(nil), "protodata.FindTelegrafConfigsRequest")
	proto.RegisterType((*FindTelegrafConfigsResponse)(nil), "protodata.FindTelegrafConfigsResponse")
	proto.RegisterType((*CreateTelegrafConfigRequest)(nil), "protodata.CreateTelegrafConfigRequest")
	proto.RegisterType((*CreateTelegrafConfigResponse)(nil), "protodata.CreateTelegrafConfigResponse")
	proto.RegisterType((*DuplicateTelegrafConfigRequest)(nil), "protodata.DuplicateTelegrafConfigRequest")
	proto.RegisterType((*DuplicateTelegrafConfigResponse)(nil), "protodata.DuplicateTelegrafConfigResponse")
	proto.RegisterType((*UpdateTelegrafConfigRequest)(nil), "protodata.UpdateTelegrafConfigRequest")
	proto.RegisterType((*UpdateTelegrafConfigResponse)(nil), "protodata.UpdateTelegrafConfigResponse")
	proto.RegisterType((*RemoveTelegrafConfigRequest)(nil), "protodata.RemoveTelegrafConfigRequest")
	proto.RegisterType((*RemoveTelegrafConfigResponse)(nil), "protodata.RemoveTelegrafConfigResponse")
	proto.RegisterType((*SetDefaultTelegrafConfigRequest)(nil), "protodata.SetDefaultTelegrafConfigRequest")
	proto.RegisterType((*SetDefaultTelegrafConfigResponse)(nil), "protodata.SetDefaultTelegrafConfigResponse")
}

func init() { proto.RegisterFile("telegraf_config.proto", fileDescriptor_3591d3dd1cc41165) }

var fileDescriptor_3591d3dd1cc41165 = []byte{
	// 596 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xdd, 0x6e, 0xda, 0x30,
	0x18, 0xc5, 0x85, 0x56, 0xe5, 0xdb, 0xaf, 0x3c, 0xda, 0x65, 0xa1, 0x83, 0xcc, 0xda, 0x0f, 0x65,
	0x12, 0x17, 0xdd, 0x13, 0x20, 0xd0, 0xaa, 0x5e, 0x4d, 0x4a, 0xbb, 0xeb, 0x29, 0x05, 0x03, 0x91,
	0x82, 0xc3, 0x12, 0xa7, 0xd3, 0xf6, 0x06, 0xbb, 0xdf, 0xcd, 0xa4, 0xed, 0x71, 0xf6, 0x5e, 0x13,
	0x4e, 0x16, 0xd9, 0x99, 0x9d, 0x80, 0x54, 0x55, 0x5c, 0x41, 0x92, 0xe3, 0xef, 0x9c, 0x63, 0xfb,
	0x3b, 0x1f, 0x1c, 0x71, 0x1a, 0xd0, 0x79, 0xe4, 0xcd, 0x3e, 0x4d, 0x42, 0x36, 0xf3, 0xe7, 0x83,
	0x55, 0x14, 0xf2, 0x10, 0x37, 0xc5, 0xcf, 0xd4, 0xe3, 0x9e, 0x7d, 0x9f, 0x32, 0xee, 0xf3, 0xaf,
	0xe9, 0x07, 0x1b, 0xbc, 0x84, 0x2f, 0xd2, 0xff, 0xe4, 0x07, 0x82, 0xee, 0x39, 0xe5, 0x57, 0x59,
	0x85, 0x91, 0x28, 0xf0, 0x81, 0x0d, 0xe7, 0x94, 0x71, 0x97, 0x7e, 0x4e, 0x68, 0xcc, 0xf1, 0x29,
	0x34, 0xd6, 0x2b, 0x2c, 0xe4, 0xa0, 0xde, 0xbd, 0xb3, 0xa3, 0x41, 0x5e, 0x77, 0x70, 0x45, 0x99,
	0xc7, 0xf8, 0x30, 0xe1, 0x0b, 0x57, 0x40, 0xb0, 0x0d, 0x87, 0x8b, 0x30, 0xe6, 0xcc, 0x5b, 0x52,
	0x6b, 0xcf, 0x41, 0xbd, 0xa6, 0x9b, 0x3f, 0xe3, 0x3e, 0x3c, 0xe6, 0x0a, 0xcd, 0xc5, 0xd8, 0xaa,
	0x3b, 0xa8, 0xb7, 0xef, 0xfe, 0xf7, 0x9e, 0x50, 0x70, 0xcc, 0xaa, 0xe2, 0x55, 0xc8, 0x62, 0x8a,
	0x87, 0xf0, 0x50, 0x5d, 0x97, 0x09, 0x7c, 0xa6, 0x08, 0x94, 0x01, 0x6e, 0x61, 0x01, 0xf9, 0xa2,
	0x37, 0x3f, 0x5d, 0xfa, 0xec, 0x9f, 0xf9, 0x9e, 0x62, 0xbe, 0x25, 0xd5, 0x16, 0x30, 0xc9, 0xbb,
	0xce, 0xdf, 0xde, 0x76, 0xfe, 0x52, 0xe2, 0xdb, 0xf3, 0x77, 0x01, 0xcf, 0xdf, 0xfb, 0x6c, 0x3a,
	0x0c, 0x02, 0x15, 0x18, 0x6f, 0xed, 0x8e, 0x50, 0xe8, 0x98, 0x4a, 0x65, 0x7a, 0x47, 0xf0, 0x48,
	0xa5, 0x8f, 0x2d, 0xe4, 0xd4, 0xcb, 0x05, 0x17, 0x57, 0x90, 0x73, 0xb0, 0xd7, 0x34, 0x06, 0xb9,
	0x9b, 0xdf, 0x44, 0x72, 0x0d, 0x6d, 0x6d, 0xa1, 0xdb, 0x14, 0xfb, 0x13, 0x41, 0x7b, 0x14, 0x51,
	0x8f, 0xd3, 0x02, 0x72, 0xeb, 0xbb, 0xf3, 0x12, 0x1e, 0x7c, 0x5b, 0x86, 0x6c, 0x38, 0x99, 0x84,
	0x09, 0xe3, 0xd9, 0xc5, 0x69, 0xba, 0xea, 0x4b, 0x8c, 0xa1, 0x21, 0x3a, 0xab, 0x2e, 0x3e, 0x8a,
	0xff, 0xf8, 0x18, 0x0e, 0xd2, 0xae, 0xb7, 0x1a, 0xe2, 0x6d, 0xf6, 0x44, 0x3a, 0x70, 0xa2, 0x97,
	0x96, 0x6e, 0x00, 0xf9, 0x85, 0xa0, 0x33, 0x4e, 0x56, 0x81, 0x3f, 0xb9, 0x33, 0xf9, 0xdb, 0x04,
	0xc0, 0x0b, 0xe8, 0x1a, 0xd5, 0x65, 0x0e, 0xfe, 0x20, 0x68, 0x7f, 0x5c, 0x4d, 0x77, 0x51, 0x7e,
	0x7e, 0x52, 0x0d, 0xed, 0x49, 0xed, 0x17, 0x4f, 0x4a, 0x6f, 0x23, 0xf3, 0xb9, 0xbe, 0x65, 0x2e,
	0x5d, 0x86, 0x37, 0x3b, 0x78, 0x4c, 0x1d, 0x38, 0xd1, 0x4b, 0xcb, 0xb4, 0xff, 0x46, 0xd0, 0xbd,
	0xa4, 0x7c, 0x4c, 0x67, 0x5e, 0x12, 0xf0, 0xdd, 0xd3, 0x4f, 0xc0, 0x31, 0xcb, 0x4b, 0x3d, 0x9c,
	0x7d, 0x3f, 0x84, 0x96, 0xfa, 0xe9, 0x92, 0x46, 0x37, 0x34, 0xc2, 0x09, 0x58, 0xa6, 0x21, 0x85,
	0xfb, 0x92, 0x8d, 0x8a, 0xf9, 0x6a, 0xbf, 0xdd, 0x08, 0x9b, 0xed, 0x68, 0xcd, 0x44, 0xbb, 0xde,
	0xab, 0x4a, 0x5a, 0x69, 0xb2, 0x55, 0xd2, 0xca, 0xc3, 0x88, 0xd4, 0x70, 0x08, 0xc7, 0xfa, 0x01,
	0x80, 0x7b, 0x52, 0xa1, 0xd2, 0x71, 0x63, 0x9f, 0x6e, 0x80, 0xcc, 0x09, 0x67, 0xf0, 0x44, 0x93,
	0xe0, 0xf8, 0x55, 0xa1, 0x86, 0x81, 0xea, 0x75, 0x15, 0x2c, 0xe7, 0xf1, 0xa1, 0xa5, 0x4b, 0x4a,
	0x2c, 0x57, 0x28, 0x49, 0x79, 0xfb, 0x4d, 0x25, 0x2e, 0xa7, 0x8a, 0xe0, 0xa9, 0x21, 0xd5, 0xb0,
	0xbc, 0x35, 0xe5, 0xb9, 0x6c, 0xf7, 0x37, 0x81, 0xca, 0xf6, 0x74, 0xf1, 0xa2, 0xd8, 0x2b, 0x89,
	0x51, 0xc5, 0x5e, 0x69, 0x4e, 0x09, 0x2a, 0x5d, 0x1a, 0x28, 0x54, 0x25, 0x49, 0xa6, 0x50, 0x95,
	0xc6, 0x8a, 0x68, 0x02, 0x53, 0xe3, 0x2a, 0x4d, 0x50, 0x11, 0x3e, 0x4a, 0x13, 0x54, 0x25, 0x01,
	0xa9, 0x5d, 0x1f, 0x08, 0xf4, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x61, 0xce, 0x1e, 0x83,
	0x73, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TelegrafConfigServerClient is the client API for TelegrafConfigServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TelegrafConfigServerClient interface {
	GetTelegrafConfigOnAgent(ctx context.Context, in *GetTelegrafConfigOnAgentRequest, opts ...grpc.CallOption) (*GetTelegrafConfigOnAgentResponse, error)
	GetTelegrafConfigOnAdmin(ctx context.Context, in *GetTelegrafConfigOnAdminRequest, opts ...grpc.CallOption) (*GetTelegrafConfigOnAdminResponse, error)
	FindAllTelegrafConfigs(ctx context.Context, in *FindAllTelegrafConfigsRequest, opts ...grpc.CallOption) (*FindAllTelegrafConfigsResponse, error)
	FindTelegrafConfigs(ctx context.Context, in *FindTelegrafConfigsRequest, opts ...grpc.CallOption) (*FindTelegrafConfigsResponse, error)
	CreateTelegrafConfig(ctx context.Context, in *CreateTelegrafConfigRequest, opts ...grpc.CallOption) (*CreateTelegrafConfigResponse, error)
	DuplicateTelegrafConfig(ctx context.Context, in *DuplicateTelegrafConfigRequest, opts ...grpc.CallOption) (*DuplicateTelegrafConfigResponse, error)
	UpdateTelegrafConfig(ctx context.Context, in *UpdateTelegrafConfigRequest, opts ...grpc.CallOption) (*UpdateTelegrafConfigResponse, error)
	RemoveTelegrafConfig(ctx context.Context, in *RemoveTelegrafConfigRequest, opts ...grpc.CallOption) (*RemoveTelegrafConfigResponse, error)
	SetDefaultTelegrafConfig(ctx context.Context, in *SetDefaultTelegrafConfigRequest, opts ...grpc.CallOption) (*SetDefaultTelegrafConfigResponse, error)
}

type telegrafConfigServerClient struct {
	cc *grpc.ClientConn
}

func NewTelegrafConfigServerClient(cc *grpc.ClientConn) TelegrafConfigServerClient {
	return &telegrafConfigServerClient{cc}
}

func (c *telegrafConfigServerClient) GetTelegrafConfigOnAgent(ctx context.Context, in *GetTelegrafConfigOnAgentRequest, opts ...grpc.CallOption) (*GetTelegrafConfigOnAgentResponse, error) {
	out := new(GetTelegrafConfigOnAgentResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/GetTelegrafConfigOnAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) GetTelegrafConfigOnAdmin(ctx context.Context, in *GetTelegrafConfigOnAdminRequest, opts ...grpc.CallOption) (*GetTelegrafConfigOnAdminResponse, error) {
	out := new(GetTelegrafConfigOnAdminResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/GetTelegrafConfigOnAdmin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) FindAllTelegrafConfigs(ctx context.Context, in *FindAllTelegrafConfigsRequest, opts ...grpc.CallOption) (*FindAllTelegrafConfigsResponse, error) {
	out := new(FindAllTelegrafConfigsResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/FindAllTelegrafConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) FindTelegrafConfigs(ctx context.Context, in *FindTelegrafConfigsRequest, opts ...grpc.CallOption) (*FindTelegrafConfigsResponse, error) {
	out := new(FindTelegrafConfigsResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/FindTelegrafConfigs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) CreateTelegrafConfig(ctx context.Context, in *CreateTelegrafConfigRequest, opts ...grpc.CallOption) (*CreateTelegrafConfigResponse, error) {
	out := new(CreateTelegrafConfigResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/CreateTelegrafConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) DuplicateTelegrafConfig(ctx context.Context, in *DuplicateTelegrafConfigRequest, opts ...grpc.CallOption) (*DuplicateTelegrafConfigResponse, error) {
	out := new(DuplicateTelegrafConfigResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/DuplicateTelegrafConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) UpdateTelegrafConfig(ctx context.Context, in *UpdateTelegrafConfigRequest, opts ...grpc.CallOption) (*UpdateTelegrafConfigResponse, error) {
	out := new(UpdateTelegrafConfigResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/UpdateTelegrafConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) RemoveTelegrafConfig(ctx context.Context, in *RemoveTelegrafConfigRequest, opts ...grpc.CallOption) (*RemoveTelegrafConfigResponse, error) {
	out := new(RemoveTelegrafConfigResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/RemoveTelegrafConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *telegrafConfigServerClient) SetDefaultTelegrafConfig(ctx context.Context, in *SetDefaultTelegrafConfigRequest, opts ...grpc.CallOption) (*SetDefaultTelegrafConfigResponse, error) {
	out := new(SetDefaultTelegrafConfigResponse)
	err := c.cc.Invoke(ctx, "/protodata.TelegrafConfigServer/SetDefaultTelegrafConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TelegrafConfigServerServer is the server API for TelegrafConfigServer service.
type TelegrafConfigServerServer interface {
	GetTelegrafConfigOnAgent(context.Context, *GetTelegrafConfigOnAgentRequest) (*GetTelegrafConfigOnAgentResponse, error)
	GetTelegrafConfigOnAdmin(context.Context, *GetTelegrafConfigOnAdminRequest) (*GetTelegrafConfigOnAdminResponse, error)
	FindAllTelegrafConfigs(context.Context, *FindAllTelegrafConfigsRequest) (*FindAllTelegrafConfigsResponse, error)
	FindTelegrafConfigs(context.Context, *FindTelegrafConfigsRequest) (*FindTelegrafConfigsResponse, error)
	CreateTelegrafConfig(context.Context, *CreateTelegrafConfigRequest) (*CreateTelegrafConfigResponse, error)
	DuplicateTelegrafConfig(context.Context, *DuplicateTelegrafConfigRequest) (*DuplicateTelegrafConfigResponse, error)
	UpdateTelegrafConfig(context.Context, *UpdateTelegrafConfigRequest) (*UpdateTelegrafConfigResponse, error)
	RemoveTelegrafConfig(context.Context, *RemoveTelegrafConfigRequest) (*RemoveTelegrafConfigResponse, error)
	SetDefaultTelegrafConfig(context.Context, *SetDefaultTelegrafConfigRequest) (*SetDefaultTelegrafConfigResponse, error)
}

func RegisterTelegrafConfigServerServer(s *grpc.Server, srv TelegrafConfigServerServer) {
	s.RegisterService(&_TelegrafConfigServer_serviceDesc, srv)
}

func _TelegrafConfigServer_GetTelegrafConfigOnAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelegrafConfigOnAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).GetTelegrafConfigOnAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/GetTelegrafConfigOnAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).GetTelegrafConfigOnAgent(ctx, req.(*GetTelegrafConfigOnAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_GetTelegrafConfigOnAdmin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelegrafConfigOnAdminRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).GetTelegrafConfigOnAdmin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/GetTelegrafConfigOnAdmin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).GetTelegrafConfigOnAdmin(ctx, req.(*GetTelegrafConfigOnAdminRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_FindAllTelegrafConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllTelegrafConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).FindAllTelegrafConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/FindAllTelegrafConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).FindAllTelegrafConfigs(ctx, req.(*FindAllTelegrafConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_FindTelegrafConfigs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindTelegrafConfigsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).FindTelegrafConfigs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/FindTelegrafConfigs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).FindTelegrafConfigs(ctx, req.(*FindTelegrafConfigsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_CreateTelegrafConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTelegrafConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).CreateTelegrafConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/CreateTelegrafConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).CreateTelegrafConfig(ctx, req.(*CreateTelegrafConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_DuplicateTelegrafConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DuplicateTelegrafConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).DuplicateTelegrafConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/DuplicateTelegrafConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).DuplicateTelegrafConfig(ctx, req.(*DuplicateTelegrafConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_UpdateTelegrafConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTelegrafConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).UpdateTelegrafConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/UpdateTelegrafConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).UpdateTelegrafConfig(ctx, req.(*UpdateTelegrafConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_RemoveTelegrafConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTelegrafConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).RemoveTelegrafConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/RemoveTelegrafConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).RemoveTelegrafConfig(ctx, req.(*RemoveTelegrafConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TelegrafConfigServer_SetDefaultTelegrafConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultTelegrafConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TelegrafConfigServerServer).SetDefaultTelegrafConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protodata.TelegrafConfigServer/SetDefaultTelegrafConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TelegrafConfigServerServer).SetDefaultTelegrafConfig(ctx, req.(*SetDefaultTelegrafConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TelegrafConfigServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protodata.TelegrafConfigServer",
	HandlerType: (*TelegrafConfigServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTelegrafConfigOnAgent",
			Handler:    _TelegrafConfigServer_GetTelegrafConfigOnAgent_Handler,
		},
		{
			MethodName: "GetTelegrafConfigOnAdmin",
			Handler:    _TelegrafConfigServer_GetTelegrafConfigOnAdmin_Handler,
		},
		{
			MethodName: "FindAllTelegrafConfigs",
			Handler:    _TelegrafConfigServer_FindAllTelegrafConfigs_Handler,
		},
		{
			MethodName: "FindTelegrafConfigs",
			Handler:    _TelegrafConfigServer_FindTelegrafConfigs_Handler,
		},
		{
			MethodName: "CreateTelegrafConfig",
			Handler:    _TelegrafConfigServer_CreateTelegrafConfig_Handler,
		},
		{
			MethodName: "DuplicateTelegrafConfig",
			Handler:    _TelegrafConfigServer_DuplicateTelegrafConfig_Handler,
		},
		{
			MethodName: "UpdateTelegrafConfig",
			Handler:    _TelegrafConfigServer_UpdateTelegrafConfig_Handler,
		},
		{
			MethodName: "RemoveTelegrafConfig",
			Handler:    _TelegrafConfigServer_RemoveTelegrafConfig_Handler,
		},
		{
			MethodName: "SetDefaultTelegrafConfig",
			Handler:    _TelegrafConfigServer_SetDefaultTelegrafConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "telegraf_config.proto",
}
